variable "project" {}
variable "environment" {}
variable "vpc_id" {}
variable "public_subnet_ids" {}
variable "security_group_ids" {}
variable "ecs_cluster_name" {}
variable "memory" {}
variable "port" {}
variable "execution_role_arn" {}
variable "task_role_arn" {}
variable "container_image" {}
variable "certificate_arn" {}